baseurl: "/brain-dump"
url: "https://albertolmr.github.io"
theme: minima

header_pages:
 - index.html
 - blog.html
 - about.md

title: Brain Dump
description: >-
 "It's the process that matters. The result is really just a side-effect"
 - Shinsuke Kita

markdown: kramdown
kramdown:
  footnote_nr: 1
  parse_block_html: true
  parse_span_html: true
  toc_levels: 1..6
