baseurl: "/brain-dump"
url: "https://albertolmr.github.io"
theme: minima

header_pages:
 - index.html
 - blog.html
 - about.md

title: Brain Dump
description: >-
 "It's the process that matters. The result is really just a side-effect"
 - Shinsuke Kita
